postgresql:
  enabled: true
  postgresqlPassword: gitea

gitea:
  admin:
    username: gitea
    password: gitea
    email: gitea@example.com
  config:
    database:
      DB_TYPE: postgres
      HOST: postgresql.gitea.svc.cluster.local:5432
      NAME: gitea
      USER: postgres
      PASSWD: gitea
