apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: k8s
    ingress:
      - hostname: argocd.fetet.net
        service: https://rke2-ingress-nginx-controller-admission.kube-system.svc.cluster.local:443
      - service: http_status:404
      - hostname: example.fetet.net
        service: hello_world
