apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: k8s
    ingress:
      - hostname: argocd.fetet.net
        service: https://argocd-server.argocd.svc.cluster.local:443
        originService: https://argocd.fetet.net
      - hostname: example.fetet.net
        service: hello_world
      - service: http_status:404
