apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: k8s
    ingress:
      - hostname: argocd.fetet.net
        service: http://argpcd-server.argocd.svc.cluster.local:443
        originServerName: "argocd.fetet.net"
        noTLSVerify: true
      - hostname: example.fetet.net
        service: hello_world
      - service: http_status:404
