apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: k8s
    ingress:
      - hostname: argocd.fetet.net
        service: http://argocd-server.argocd.svc.cluster.local:443
      - hostname: example.fetet.net
        service: hello_world
      - service: http_status:404
    originRequest:
      noTLSVerify: true
