apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --origincert
            - /etc/cloudflared/cert.pem
            - run
            - --cred-file
            - /etc/cloudflared/creds.json
            - k8s
          volumeMounts:
            - name: creds
              mountPath: /etc/cloudflared/creds.json
              subPath: creds.json
              readOnly: true
            - name: certif
              mountPath: /etc/cloudflared/cert.pem
              subPath: cert.pem
              readOnly: true
            - name: config
              mountPath: /etc/cloudflared/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: cloudflared-config

        - name: creds
          secret:
            secretName: tunnel-credentials

        - name: certif
          secret:
            secretName: tunnel-certificat
