apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --origincert
            - /etc/cloudflared/cert.pem
            - run
            - --cred-file
            - /etc/cloudflared/creds.json
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared/
              subPath: /etc/cloudflared/creds.json
            - name: config
              mountPath: /etc/cloudflared/
              subPath: /etc/cloudflared/cert.pem
      volumes:
        - name: config
          configMap:
            name: cloudflared-config

